2017-04-08 08:43:58,073 [main.py:71][INFO] Using threading model...
2017-04-08 08:44:37,859 [main.py:77][INFO] Using threading model...
2017-04-08 08:44:37,864 [main.py:136][INFO] Furion server listening on ('0.0.0.0', 443), SSL OFF, AUTH ON.
2017-04-08 08:49:24,765 [socks5.py:203][INFO] Auth succeeded for user: username
2017-04-08 08:49:24,766 [socks5.py:298][INFO] Connecting to api.ipify.org.
2017-04-08 08:49:26,730 [socks5.py:266][ERROR] Error when forwarding
Traceback (most recent call last):
  File "D:\Users\Scott\Documents\Visual Studio 2015\Projects\furion\furion\socks5.py", line 260, in handle
    result = self.forward(self.request, dest)
  File "D:\Users\Scott\Documents\Visual Studio 2015\Projects\furion\furion\socks5.py", line 317, in forward
    data = readable.recv(BUF_SIZE)
error: [Errno 10054] An existing connection was forcibly closed by the remote host
2017-04-08 08:49:26,732 [socks5.py:271][INFO] 539 bytes out, 6177 bytes in. Socks5 session finished ('127.0.0.1', 50570) <-> ('23.23.117.228', 443).
